version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host diretory to internal container directory
      - ./backend/staticdjango:/staticdjango
    working_dir: /backend/

    env_file:
      - backend.env

    ports:
      - "9998:9998"
    #command: python manage.py runserver 0.0.0.0:9998
    command: >
      sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:9998"

    #    depends_on:
    #     - postgres_fazenda_rainha
    links:
      - postgres_fazenda_rainha

  nginx:
    image: nginx:latest
    ports:
      - 9999:9999
    volumes:
      - ./backend/staticdjango:/backend/staticdjango
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend

    depends_on:
      - backend

  frontend:
    image: node:12.13.0

    # build: ./frontend
    working_dir: /frontend
    #command: sh entrypoint.sh

    volumes:
      - ./frontend/:/frontend

  postgres_fazenda_rainha:
    image: postgres:12.1
    restart: always
    env_file:
      - db.env

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432"

volumes:
  postgres-data:
